### ISSUE TITLE
Integration tests are serverspec :cry: :panda_face:

### ISSUE THREAD

**Issue by jjasghar** [adamleff/batsception-cookbook#1]
It seems https://github.com/adamleff/batsception-cookbook/blob/master/spec/unit/recipes/default_spec.rb is serverspec. I'd expect it to be BATS.

**Comment by adamleff** [comment]
BATS is an inappropriate fit for unit tests such as this.  I'll be happy to use BATSpec rather than ChefSpec if it were to be released.

Closing #1.
